### ISSUE TITLE
Allow skipping validation of DeliveryReceipt (e.g. network_error_code size)

### ISSUE THREAD

**Issue by JChrist** [RestComm/cloudhopper-smpp#15]
Hello.
I wanted to ask if this fork is being actively maintained and if there are any new versions with bug fixes coming out of it (and at which maven coordinates?).
Also, is version coming out with netty 4 (from netty4 branch) being maintained as well? 
The reason I am asking is because I am using version with netty4 and I wanted to address issue mentioned here: https://github.com/fizzed/cloudhopper-smpp/issues/10 and I would be happy to contribute for it, but I'm not at all sure if there is any currently actively maintained repo for cloudhopper.

**Comment by vetss** [comment]
Hello @JChrist 

> I wanted to ask if this fork is being actively maintained and if there are any new versions 
> with bug fixes coming out of it

Yes, this fork is being actively maintained for both master and netty-4 branches.

**Comment by JChrist** [comment]
@vetss That's good to hear!
I was thinking of providing a new method with a signature of:
static public DeliveryReceipt parseShortMessage(String shortMessage,
			DateTimeZone zone, boolean checkMissingFields, boolean validateFields)
                        throws DeliveryReceiptException

By default the existing method would delegate calls to the new one with true for validateFields (providing backwards-compatibility), meanwhile allowing one to call it with `false`, thus not throwing exceptions if field validation fails. Specifically for error code field, it will call the `setRawErrorCode` method in `DeliveryReceipt`, so as to keep the raw error code, even if it's more than 3 characters.

What do you think?

**Comment by vetss** [comment]
@JChrist sorry I am not so deeply aware for mentioned by you methods. 
Feel free to add PRs if you mean we need some fixes. Pease take into account that we need updates for both master and netty-4 branches if an update is for staff in both branches

**Comment by vetss** [comment]
Hello @JChrist 

I added your upadate into master and netty4 branches:
https://github.com/RestComm/cloudhopper-smpp/pull/18

And I also added "slf4j.version" into a root pom.

Thanks for your work. I see that you provide abackup compatibility that is good.
Please provide your testing results.

**Comment by vetss** [comment]
@JChrist 

Here are binaries for netty4 branch:
https://mobicents.ci.cloudbees.com/view/SS7/job/Restcomm-Cloudhopper-SMPP/12/

**Comment by JChrist** [comment]
thanks a lot @vetss for your help and review!
